export const SpotifyConstant = {
    SET_TOKEN: 'SET_TOKEN',
    SET_USERS: 'SETUSERS',
    SET_TOPTRACKSSHORT: 'SET_TOPTRACKSSHORT',
    SET_TOPTRACKSMID: 'SET_TOPTRACKSMID',
    SET_TOPTRACKSLONG: 'SET_TOPTRACKSLONG',
    SET_RELATED: 'SET_RELATED'
};